### ISSUE TITLE
No test pcap files

### ISSUE THREAD

**Issue by jensgreen** [rtslab/EnergyBox#10]
The tests look for pcap files, which do not exist. The same goes for `grade runCli`.

Would be great if someone could capture som traffic, push the pcap files and make sure the tests pass.

**Comment by ekhve37** [comment]
I can add a couple of small pcap files. Should we create a folder "test" and place them there, or just add them to the config folder (which is copied when using gradle). 

In the new push I don't suggest to use gradle runCli since it uses another path and it does not find the jnetpcap.dll in Windows. I guess it works for the other operating systems.

**Comment by jensgreen** [comment]
Great! `src/test/resources/` seems like a good place for the pcaps, no?

runCli should probably be removed if it's not useful any more.

**Comment by ekhve37** [comment]
I added two small pcap files.
